language: objective-c

install:
  - brew install neko haxe
  - cd ..
  - mkdir haxelib
  - haxelib setup haxelib
  - haxelib install hxcpp 3.1.68 > /dev/null
  - haxelib install hamcrest 1.2.1 > /dev/null
  - haxelib install munit 2.1.0 > /dev/null
before_script:
  - cd $TRAVIS_BUILD_DIR
script:
  - haxelib run munit test -cpp